version: "3.9"

services:
  app:
    build: .
    container_name: bencorp_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./bencorp.db:/app/bencorp.db
    env_file:
      - .env
